features:
    modality: "audio"
    type: "all"
model_type: "classifier"
ground_truths:
    type: "aggregates"
    path: "../data/all_tickers/concatenated_final.csv"
text_embeddings:
    out_folder: "../data/text_embeddings"
    model: "MiniLM"
audio_embeddings:
    out_folder: "../data/audio_embeddings"
lstm:
    num_sequence_months: 3
    ticker_mode: 'same'
    epochs: 200
    lr: 0.0001
    batch_size: 64
    hidden_size: 128
    num_layers: 1
    linear_size: 512
    patience: 100
